In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

ModuleNotFoundError: No module named 'pandas'

In [ ]:

url = "https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/master/data.csv"
df = pd.read_csv(url)

df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [ ]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

## Train Test Split

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

## Scaling

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train

array([[-0.16639541, -1.16501569, -0.18306204, ...,  0.23878936,
         0.15958945, -0.62146429],
       [-0.12633604, -0.69817088, -0.17061387, ..., -0.40078109,
        -0.13157167, -0.32190557],
       [ 1.59049386,  0.5696564 ,  1.5779398 , ...,  1.71978704,
         1.97806948, -0.24400884],
       ...,
       [-0.04621731, -0.5275474 , -0.01833119, ...,  0.37050167,
         0.31453485, -0.22167081],
       [-1.15643398, -0.9872829 , -1.16646788, ..., -1.57424585,
         0.0846708 , -0.37059102],
       [ 0.60617805, -0.11994685,  0.70241815, ...,  0.91879243,
        -0.19286875,  1.30934348]])

In [ ]:
X_test

array([[ 0.57470283, -0.33085644,  0.6277291 , ...,  1.12095551,
         2.36117623,  2.28305253],
       [-0.65283054, -0.07966075, -0.67891435, ..., -0.67507963,
        -0.59300247, -0.20105109],
       [ 1.52182066, -0.108098  ,  1.50325075, ...,  1.42113704,
         0.65166879,  0.38088326],
       ...,
       [-1.25429328, -1.73139087, -1.27103255, ..., -1.73383216,
         0.37753463, -0.11055343],
       [ 0.60903943,  0.05541617,  0.74391206, ...,  0.98464859,
         0.74020901,  0.45362505],
       [-0.69002852, -0.9067107 , -0.69883143, ..., -0.52943032,
        -0.20138224, -0.30815909]])

In [ ]:
y_train

19     B
532    B
343    M
45     M
480    B
      ..
210    M
484    B
255    M
185    B
283    M
Name: diagnosis, Length: 455, dtype: object

## Label Encoding

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
y_train

array([0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1])

## Numpy arrays to pyTorch tensors

In [ ]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

In [ ]:
y_train_tensor.shape

torch.Size([455])

## Defining the model

In [ ]:
class MySimpleNN():
    def __init__(self,X):
        self.weights = torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
        self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)
    
    def forward(self,X):
        z = torch.matmul(X,self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    def loss_function(self, y_pred, y):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss

## Important Parameters

In [ ]:
learning_rate = 0.1
num_epochs = 25

## Training pipeline

In [ ]:
# create model
model = MySimpleNN(X_train_tensor)
# define loop
for epoch in range(num_epochs):
    # forward pass
    y_pred = model.forward(X_train_tensor)

    # loss calculate
    loss = model.loss_function(y_pred,y_train_tensor)
    

    # backward pass
    loss.backward()

    # parameter update
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    # zero gradient
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # Print loss in each epoch
    print(f"Epoch: {epoch + 1},loss {loss.item():.4f}")

Epoch: 1,loss 3.4343
Epoch: 2,loss 3.3050
Epoch: 3,loss 3.1725
Epoch: 4,loss 3.0334
Epoch: 5,loss 2.8847
Epoch: 6,loss 2.7313
Epoch: 7,loss 2.5723
Epoch: 8,loss 2.4083
Epoch: 9,loss 2.2484
Epoch: 10,loss 2.0894
Epoch: 11,loss 1.9313
Epoch: 12,loss 1.7725
Epoch: 13,loss 1.6226
Epoch: 14,loss 1.4794
Epoch: 15,loss 1.3489
Epoch: 16,loss 1.2331
Epoch: 17,loss 1.1338
Epoch: 18,loss 1.0521
Epoch: 19,loss 0.9875
Epoch: 20,loss 0.9380
Epoch: 21,loss 0.9008
Epoch: 22,loss 0.8727
Epoch: 23,loss 0.8510
Epoch: 24,loss 0.8336
Epoch: 25,loss 0.8192

In [ ]:
model.bias

tensor([-0.1695], dtype=torch.float64, requires_grad=True)

In [ ]:
model.weights

tensor([[ 0.1548],
        [-0.0245],
        [-0.2466],
        [-0.2294],
        [-0.2587],
        [ 0.1297],
        [-0.2785],
        [-0.1392],
        [ 0.1028],
        [-0.1224],
        [-0.2911],
        [ 0.4392],
        [-0.1173],
        [ 0.0821],
        [ 0.4787],
        [ 0.1537],
        [ 0.4174],
        [ 0.4086],
        [ 0.0889],
        [-0.2379],
        [ 0.2754],
        [ 0.3262],
        [ 0.1205],
        [ 0.0393],
        [ 0.0553],
        [ 0.2892],
        [-0.4983],
        [ 0.1555],
        [ 0.4772],
        [-0.3151]], dtype=torch.float64, requires_grad=True)

## Evaluation

In [ ]:
# Model Evaluation
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy : {accuracy.item()}")

Accuracy : 0.5166205167770386